export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_ALL_BRAND = "GET_ALL_BRAND";

export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const CREATE_PRODUCTS = "CREATE_PRODUCTS";
export const GET_PRODUCT_LIKE = "GET_PRODUCT_LIKE";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT_DETALIS = "GET_PRODUCT_DETALIS";

export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const LOGIN_USER = "LOGIN_USER";
